# Generated by Django 5.1.3 on 2025-03-19 01:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, max_length=100, populate_from="name", unique=True
            ),
        ),
    ]
