name: Deploy Django to EC2

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/django-app  # Change to your project directory
          git pull origin main
          pip install -r requirements.txt  # Install dependencies
          python manage.py migrate  # Run migrations
          python manage.py collectstatic --noinput  # Collect static files
          sudo systemctl restart gunicorn  # Restart Gunicorn service
          sudo systemctl restart nginx  # Restart Nginx
          EOF
